SocialGruppo4/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using SocialGruppo4.Models.Utenti;

namespace SocialGruppo4.Controllers
{
    public class AuthController : Controller
    {
        // DOC: Vista per visualizzare la pagina di Login.
        // Se l'utente ha già effettuato l'accesso viene reindirizzato
        // alla pagina Home.
        [HttpGet("accedi")]
        public IActionResult Index()
        {
            if (HttpContext.Items["User"] is not null)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>
                {
                    {"Status", "error"},
                    {"Message", "Hai già effettuato l'accesso"}
                };
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // DOC: Metodo POST che risponde al submit della form di Login.
        // Riceve come parametro il modello usato nella vista Login e
        // controlla che non ci siano errori di validazioni come dichiarato
        // nel modello FormAccedi.
        // Quando l'utente inserisce l'email e la password corretta, viene
        // salvato il cookie di autenticazione nella Response da restituire.
        // Altrimenti, riceve il messaggio di errore.
        [HttpPost("accedi")]
        public IActionResult Index(FormAccedi form)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Utente? utente = (Utente?)DAOUtenti.GetInstance().Find(form.Email!, form.Password!);

            if (utente is null)
            {
                TempData.Add("Message", "La combinazione di Email e Password non è stata riconosciuta.");
                return RedirectToAction("Index");
            }

            CookieOptions cookieOpts = new()
            {
                Expires = DateTime.Now.AddYears(1),
                HttpOnly = true,
                Secure = true,
                SameSite = SameSiteMode.Lax
            };

            Response.Cookies.Append("auth", utente.Id.ToString(), cookieOpts);

            return RedirectToAction("Index", "Home");
        }

        // DOC: Vista della pagina di registrazione di un nuovo dipendente.
        // Il metodo fa particolare attenzione a controllare che l'utente
        // sia loggato e che abbia l'autorizzazione per poter inserire nuovi
        // utenti sulla piattaforma.
        [HttpGet("registra-dipendente")]
        public IActionResult RegistraDipendente()
        {
            var utente = (Utente?)HttpContext.Items["User"];

            if (utente is null)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>
                {
                    {"Status", "error"},
                    {"Message", "Accedi al tuo account per poter visualizzare la pagina."}
                };
                return RedirectToAction("Index");
            }
            else if (!utente.Amministratore)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>
                {
                    {"Status", "error"},
                    {"Message", "Non hai i giusti permessi per poter visualizzare la pagina."}
                };
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // DOC: Metodo POST per la registrazione di un nuovo dipendente.
        // Come parametro riceve il modello con le annotazioni di validazione
        // per controllare che i dati della form siano corretti.
        // Se alcuni dati (email, numero o codice fiscale) sono già presenti in
        // database, l'amministrazione riceve un errore.
        [HttpPost("registra-dipendente")]
        public IActionResult RegistraDipendente(FormRegistraDipendente form)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Utente utente = new()
            {
                Nominativo = form.Nominativo!,
                Email = form.Email!,
                CodiceFiscale = form.CodiceFiscale!,
                Numero = form.Numero!,
                Residenza = form.Residenza ?? "",
                Amministratore = false,
                PasswordHash = Utente.GetRandomPassword(12)
            };

            var success = DAOUtenti.GetInstance().Insert(utente);
            if (!success)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>
                {
                    {"Status", "error"},
                    {"Message", "ERRORE: è stato già registrato un dipendente con questi dati."}
                };
                return View();
            }

            TempData["FlashMessage"] = new Dictionary<string, string>
            {
                {"Status", "success"},
                {"Message", $"Il dipendente {utente.Nominativo} è stato registrato con successo!"}
            };
            return RedirectToAction("Index", "Home");
        }


        // DOC: Questo metodo effettua il logout dell'utente tramite
        // l'eliminazione del cookie di autenticazione creato in precedenza.
        [HttpPost("logout")]
        public IActionResult Logout()
        {
            Response.Cookies.Delete("auth");
            return RedirectToAction("Index", "Home");
        }

        // DOC: Vista della pagina del recupero account di un utente.
        // Ovviamente non è usabile una cosa del genere in production,
        // ma per semplicità abbiamo optato per questa soluzione.
        [HttpGet("recupera-account")]
        public IActionResult RecuperaAccount()
        {
            return View();
        }

        // DOC: Metodo POST della form di recupero account.
        // Il modello ricevuto come parametro contiene alcune annotazioni
        // di base per la validazione. Tramite l'inserimento di un email
        // è possibile reimpostare la password, ridando l'accesso
        // all'utente.
        [HttpPost("recupera-account")]
        public IActionResult RecuperaAccount(FormRecuperaAccount form)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Utente? utente = (Utente?)DAOUtenti.GetInstance().Find(form.Email!);

            if (utente is null)
            {
                TempData.Add("Message", $"Utente con email {form.Email!} non trovato.");
                return RedirectToAction("RecuperaAccount");
            }

            DAOUtenti.GetInstance().UpdatePassword(form.Email!, form.Password!);

            return RedirectToAction("Index");
        }
    }
}

SocialGruppo4/Controllers/ProfiloController.cs
using Microsoft.AspNetCore.Mvc;
using SocialGruppo4.Models.Post;
using SocialGruppo4.Models.Utenti;

namespace SocialGruppo4.Controllers
{
    public class ProfiloController : Controller
    {
        public IActionResult Index()
        {
            Utente? utente = (Utente?)HttpContext.Items["User"];
            if (utente is null)
            {
                return RedirectToAction("Index", "Auth");
            }

            ViewBag.Posts = DAOPost.GetInstance().MyLatest(utente.Id);

            return View(utente);
        }
    }
}

SocialGruppo4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="it" class="h-full">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialGruppo4</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>

<body class="h-full">
    <header class="navbar">
        <div class="navbar-container container">
            <a id="logo" asp-controller="Home" asp-action="Index">Social</a>
            <nav>
                <div class="navbar-items">
                    <a asp-controller="Home" asp-action="Index">Home</a>
                    <a href="Utenti/ElencoUtenti">Utenti</a>
                </div>
                @if (ViewBag.User is not null)
                {
                    <div class="dropdown">
                        <button class="dropbtn">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="24"
                                height="24">
                                <path fill-rule="evenodd"
                                    d="M3 6.75A.75.75 0 013.75 6h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 6.75zM3 12a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 12zm0 5.25a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"
                                    clip-rule="evenodd" />
                            </svg>
                        </button>
                        <div class="dropdown-content">
                            <a asp-controller="Profilo" asp-action="Index" class="dropdown-item">
                                Profilo
                            </a>
                            @if (ViewBag.User.Amministratore)
                            {
                                <a asp-controller="Auth" asp-action="RegistraDipendente" class="dropdown-item">
                                    Registra dipendente
                                </a>
                            }
                            <form asp-controller="Auth" asp-action="Logout" method="POST">
                                <button id="logout" type="submit" class="dropdown-item">Logout</button>
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <a asp-controller="Auth" asp-action="Index" class="navbar-item">Accedi</a>
                }
            </nav>
        </div>
    </header>

    <main class="flex-grow">
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer>
        <div class="container">
            Progetto Social - Gruppo 4
        </div>
    </footer>

    @if (TempData.ContainsKey("FlashMessage"))
    {
        var fm = TempData["FlashMessage"] as Dictionary<string, string>;
        string status = @fm?["Status"]!;
        string message = @fm?["Message"]!;
        <div class="flash-message flash-@status">
            <p>@message</p>
            <button type="button" onclick="closeFlashMessage(event)">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd"
                        d="M5.47 5.47a.75.75 0 011.06 0L12 10.94l5.47-5.47a.75.75 0 111.06 1.06L13.06 12l5.47 5.47a.75.75 0 11-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 01-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 010-1.06z"
                        clip-rule="evenodd" />
                </svg>
            </button>
        </div>
    }

    <script src=" ~/js/site.js" asp-append-version="true">
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>