SocialGruppo4/Controllers/HomeController.cs
 using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SocialGruppo4.Models;
using SocialGruppo4.Models.Likes;
using SocialGruppo4.Models.Post;
using SocialGruppo4.Models.Utenti;
using Utility;

namespace SocialGruppo4.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IHostEnvironment _env;

    public HomeController(ILogger<HomeController> logger, IHostEnvironment env)
    {
        _logger = logger;
        _env = env;
    }

    public IActionResult Index()
    {
        Entity? utente = (Entity?)HttpContext.Items["User"];
        ViewBag.Likes = new List<int>();

        if (utente is not null)
        {
            ViewBag.Utenti = DAOUtenti.GetInstance().LatestToFollow(limit: 6, idUtente: utente.Id);
            ViewBag.Likes = DAOLikes.GetInstance().ReadUserLikedPosts(utente.Id);
            ViewBag.Posts = DAOPost.GetInstance().LatestFollowing(utente.Id);
        }
        else
        {
            ViewBag.Posts = DAOPost.GetInstance().Latest();
        }

        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CreaPost()
    {
        Utente? utente = (Utente?)HttpContext.Items["User"];
        if (utente is null)
        {
            TempData["FlashMessage"] = new Dictionary<string, string>()
            {
                {"Status", "error"},
                {"Message", "Devi accedere con il tuo account prima di poter pubblicare un post."}
            };
            return RedirectToAction("Index");
        }

        IFormFile? imageFile = Request.Form.Files["imageFile"];
        if (imageFile is not null)
        {
            string path = Path.Combine(_env.ContentRootPath, "wwwroot", "images", "posts", imageFile.FileName);
            using var fileStream = new FileStream(path, FileMode.Create);
            imageFile.CopyTo(fileStream);
        }

        Post post = new()
        {
            IdUtente = utente.Id,
            IdPadre = null,
            Contenuto = Request.Form["contenuto"],
            DataEora = DateTime.Now,
            MiPiace = 0,
            Immagine = imageFile?.FileName
        };

        bool success = DAOPost.GetInstance().Insert(post);
        if (!success)
        {
            TempData["FlashMessage"] = new Dictionary<string, string>()
            {
                {"Status", "error"},
                {"Message", "Qualcosa è andato storto. Riprova più tardi."}
            };
            return RedirectToAction("Index");
        }

        TempData["FlashMessage"] = new Dictionary<string, string>()
        {
            {"Status", "success"},
            {"Message", "Il tuo post è stato pubblicato con successo!"}
        };
        return RedirectToAction("Index");
    }

    [HttpPost("posts/{id:int}/like")]
    public IActionResult ToggleLike(int id)
    {
        Entity? utente = (Entity?)HttpContext.Items["User"];

        if (utente is null)
        {
            return RedirectToAction("Index", "Auth");
        }

        Like like = new()
        {
            IdUtente = utente.Id,
            IdPost = id
        };

        bool success;
        List<int> userLikes = DAOLikes.GetInstance().ReadUserLikedPosts(utente.Id);

        if (userLikes.Contains(id))
        {
            success = DAOLikes.GetInstance().Delete(like);
        }
        else
        {
            success = DAOLikes.GetInstance().Insert(like);
        }

        if (!success)
        {
            TempData["FlashMessage"] = new Dictionary<string, string>()
            {
                {"Status", "error"},
                {"Message", "Qualcosa è andato storto. Riprova più tardi."}
            };
            return RedirectToAction("Index");
        }


        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SocialGruppo4/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using SocialGruppo4.Models.Likes;
using SocialGruppo4.Models.Post;
using SocialGruppo4.Models.Utenti;
using Utility;

namespace SocialGruppo4.Controllers
{
    public class PostsController : Controller
    {
        [HttpGet("Posts/Details/{id}")]
        public IActionResult Details(int id)
        {
            Console.WriteLine(id);
            Entity? utente = (Entity?)HttpContext.Items["User"];

            if (utente != null)
                ViewBag.Likes = DAOLikes.GetInstance().ReadUserLikedPosts(utente.Id);

            ViewBag.Commenti = DAOPost.GetInstance().FullPost(id);

            Post temp = (Post)DAOPost.GetInstance().Find(id);


            return View(temp);
        }
    }
}

SocialGruppo4/Controllers/UtentiController.cs
using Microsoft.AspNetCore.Mvc;
using SocialGruppo4.Models.Followers;
using SocialGruppo4.Models.Utenti;
using Utility;

namespace SocialGruppo4.Controllers
{
    public class UtentiController : Controller
    {
        public IActionResult ElencoUtenti()
        {
            List<Entity> e = DAOUtenti.GetInstance().Read();

            List<Utente> utenti = new List<Utente>();
            foreach (var entitaItem in e)
            {
                Utente utente = new Utente
                {
                    Nominativo = ((Utente)entitaItem).Nominativo,
                    Email = ((Utente)entitaItem).Email
                };
                utenti.Add(utente);
            }

            return View(utenti);
        }

        [HttpPost("utenti/follow/{id:int}")]
        public IActionResult Follow(int id)
        {
            Entity? utente = (Entity?)HttpContext.Items["User"];

            if (utente is null)
            {
                return RedirectToAction("Index", "Auth");
            }

            Utente? uFollow = (Utente?)DAOUtenti.GetInstance().Find(id);
            if (uFollow is null)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>{
                    {"Status", "error"},
                    {"Message", "Utente da seguire non trovato."}
                };

                return RedirectToAction("Index", "Home");
            }

            Follower follower = new()
            {
                IdUtente = utente.Id,
                IdFollower = id,
            };

            bool success = DAOFollower.getInstance().Insert(follower);
            if (!success)
            {
                TempData["FlashMessage"] = new Dictionary<string, string>{
                    {"Status", "error"},
                    {"Message", "Stai già seguendo questo utente."}
                };

                return RedirectToAction("Index", "Home");
            }

            TempData["FlashMessage"] = new Dictionary<string, string>{
                {"Status", "success"},
                {"Message", $"Fatto! Da ora segui {uFollow?.Nominativo}."}
            };

            return RedirectToAction("Index", "Home");
        }
    }
}

SocialGruppo4/Views/Home/Index.cshtml
@using SocialGruppo4.Models.Post
@using SocialGruppo4.Models.Utenti

@{
    ViewData["Title"] = "Home Page";
}

<div class="home-container">
    <section class="w-full">
        <!-- Inizio form post -->
        <form asp-action="CreaPost" method="POST" enctype="multipart/form-data" onsubmit="submitNuovoPost(event)">
            <input type="file" name="imageFile" accept="image/png, image/jpeg" id="post_form_image" class="hidden" />
            <textarea name="contenuto" class="post-form-textarea" rows="5"
                placeholder="A cosa stai pensando?"></textarea>
            <div class="post-form-buttons">
                <label for="post_form_image" class="icon-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="24"
                        height="24">
                        <path fill-rule="evenodd"
                            d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z"
                            clip-rule="evenodd" />
                    </svg>
                </label>
                <button type="submit" class="btn-primary">Pubblica</button>
            </div>
        </form>
        <!-- Fine form post -->

        <!-- Inizio elenco post -->
        <div class="post-container">
            @foreach (Post post in ViewBag.Posts)
            {
                <a asp-action="Details" asp-controller="Posts" asp-route-id="@post.Id" class="tweet">
                    <div class="tweet-header">
                        <p class="author">@post.Utente?.Nominativo</p>
                        <p class="date">@post.DataEora.ToString("d/M/yyyy HH:mm")</p>
                    </div>
                    @if (@post.Immagine is not null && @post.Immagine != string.Empty)
                    {
                        <img src="~/images/posts/@post.Immagine" class="w-full mb-2 rounded">
                    }
                    <p>@post.Contenuto</p>
                    <div class="actions">
                        <div class="action-container">
                            @{
                                var isLiked = ViewBag.Likes.Contains(post.Id);
                            }
                            <form asp-action="ToggleLike" asp-route-id="@post.Id" method="post">
                                <button type="submit" onmouseenter="fillLike(event, '@isLiked')"
                                    onmouseleave="unFillLike(event, '@isLiked')"
                                    class="@(isLiked ? "like-full" : "like-empty")">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5"
                                        stroke="currentColor" width="24" height="24"
                                        fill="@(isLiked ? "currentColor" : "none")">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                                    </svg>
                                </button>
                            </form>
                            <small>@post.MiPiace</small>
                        </div>
                    </div>
                </a>
            }
        </div>
        <!-- Fine elenco post -->
    </section>

    <!-- Inizio potresti conoscere -->
    @if (ViewBag.User is not null && ViewBag.Utenti.Count > 0)
    {
        <section class="home-utenti">
            <h2>Potresti conoscere</h2>
            <div class="mt-4">
                @foreach (Utente utente in ViewBag.Utenti)
                {
                    <div class="home-card-utente">
                        <h3 class="mb-2">@utente.Nominativo</h3>
                        <form asp-controller="Utenti" asp-action="Follow" asp-route-id="@utente.Id" method="POST">
                            <button type="submit" class="btn-secondary w-full">Segui</button>
                        </form>
                    </div>
                }
            </div>
            <div class="mt-4 text-right">
                <a asp-action="ElencoUtenti" asp-controller="Utenti" class="link">MOSTRA TUTTI</a>
            </div>
        </section>
    }
    <!-- Fine potresti conoscere -->
</div>